image: node:10.1

before_script:
  - apt-get update
  - apt-get install -y python3.5 python3.5-dev
  - apt-get install -y software-properties-common
  - add-apt-repository ppa:jonathonf/python-3.6
  - apt-get update
  - apt-get upgrade
  - apt-get install -y python3.6 python3.6-dev
  - apt-get install -y virtualenv virtualenvwrapper
  - which python3
  - virtualenv --no-site-packages -p /usr/bin/python3.5 py35
  - virtualenv --no-site-packages -p /usr/bin/python3.6 py36
  - source py35/bin/activate
  

pages:
  script:
    - python35 setup.py bdist_wheel sdist
    - python36 setup.py bdist_wheel sdist
    - mkdir -p public/bin
    - cp dist/* public/bin
    - ls public/bin

  artifacts:
    paths:
    - public

  only:
    - /^release\/.*$/
