image: node:10.1

before_script:
  - apt-get update
  - wget https://www.python.org/ftp/python/3.5.0/Python-3.5.0.tar.xz
  - tar Jxfv Python-3.5.0.tar.xz
  - cd Python-3.5.0
  - ./configure; make; make install
  - cd ../
  - wget https://www.python.org/ftp/python/3.6.0/Python-3.6.0.tar.xz
  - tar Jxfv Python-3.6.0.tar.xz
  - cd Python-3.6.0
  - ./configure; make; make install
  - apt-get install -y virtualenv virtualenvwrapper
  - virtualenv --no-site-packages -p /usr/local/bin/python3.5 py35
  - virtualenv --no-site-packages -p /usr/local/bin/python3.6 py36
  

pages:
  script:
    - python35 setup.py bdist_wheel sdist
    - python36 setup.py bdist_wheel sdist
    - mkdir -p public/bin
    - cp dist/* public/bin
    - ls public/bin

  artifacts:
    paths:
    - public

  only:
    - /^release\/.*$/
